#!/usr/bin/env python3
"""Extract kernel-level compute/comm breakdown from Nsight Systems sqlite traces.

This script uses CMD-level NVTX labels generated by `--trace-kernel-ground-truth`:
  <prefix>|rank=<r>|op=<op>|state=<mg_state>|stage=<s>|batch=<b>|iter=<i>

For each NVTX range, it aggregates overlapped CUDA kernels from the same process:
  - compute_kernel_ms: kernels whose names do NOT contain "nccl"
  - comm_kernel_ms: kernels whose names contain "nccl"
  - total_kernel_ms: compute + comm

The output JSON can be consumed by compare_qwen_nsys_compute_only.py.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, median
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


DEFAULT_OPS = ("forward_step", "backward_step", "optimizer_step")
GLOBAL_TID_LOCAL_MASK = (1 << 24) - 1


@dataclass(frozen=True)
class NvtxCmdRange:
    start_ns: int
    end_ns: int
    global_pid: int
    rank: int
    op: str
    mg_state: str
    stage_id: str
    batch_id: str
    iter_id: str
    label: str


@dataclass(frozen=True)
class NvtxPhaseRange:
    start_ns: int
    end_ns: int
    global_pid: int
    rank: int
    op: str
    mg_state: str
    stage_id: str
    batch_id: str
    iter_id: str
    phase: str


@dataclass(frozen=True)
class KernelRecord:
    start_ns: int
    end_ns: int
    stream_id: int
    name: str
    is_comm: bool


def parse_csv_ints(raw: str) -> Optional[List[int]]:
    if raw.strip() == "":
        return None
    values: List[int] = []
    for token in raw.split(","):
        item = token.strip()
        if not item:
            continue
        values.append(int(item))
    if not values:
        return None
    return values


def parse_csv_strs(raw: str) -> List[str]:
    values = [token.strip() for token in raw.split(",") if token.strip()]
    if not values:
        raise ValueError("Empty --ops list.")
    return values


def derive_global_pid(global_tid: int) -> int:
    """Convert NVTX globalTid into the globalPid domain used by CUPTI kernels."""
    return global_tid & (~GLOBAL_TID_LOCAL_MASK)


def parse_cmd_nvtx_label(label: str, prefix: str) -> Optional[Dict[str, str]]:
    """Parse CMD NVTX label into key/value mapping."""
    prefix_token = f"{prefix}|"
    if not label.startswith(prefix_token):
        return None
    fields = label[len(prefix_token) :].split("|")
    mapping: Dict[str, str] = {}
    for field in fields:
        if "=" not in field:
            continue
        key, value = field.split("=", 1)
        mapping[key] = value
    required = ("rank", "op", "state", "stage", "batch", "iter")
    if any(key not in mapping for key in required):
        return None
    return mapping


def range_identity(nvtx_range: NvtxCmdRange) -> Tuple[int, int, str, str, str, str, str, int, int]:
    """Build stable identity for one parent CMD NVTX range."""
    return (
        nvtx_range.global_pid,
        nvtx_range.rank,
        nvtx_range.op,
        nvtx_range.mg_state,
        nvtx_range.stage_id,
        nvtx_range.batch_id,
        nvtx_range.iter_id,
        nvtx_range.start_ns,
        nvtx_range.end_ns,
    )


def _range_meta_key(
    global_pid: int,
    rank: int,
    op: str,
    mg_state: str,
    stage_id: str,
    batch_id: str,
    iter_id: str,
) -> Tuple[int, int, str, str, str, str, str]:
    return (global_pid, rank, op, mg_state, stage_id, batch_id, iter_id)


def classify_kernel_name(kernel_name: str) -> bool:
    """Return True when kernel is communication kernel."""
    return "nccl" in kernel_name.lower()


def overlap_ns(window_start: int, window_end: int, kernel_start: int, kernel_end: int) -> int:
    lo = max(window_start, kernel_start)
    hi = min(window_end, kernel_end)
    return max(0, hi - lo)


def merge_intervals(intervals: Sequence[Tuple[int, int]]) -> List[Tuple[int, int]]:
    """Merge intervals and return a sorted, non-overlapping list."""
    if not intervals:
        return []
    sorted_intervals = sorted(intervals)
    merged: List[Tuple[int, int]] = []
    cur_start, cur_end = sorted_intervals[0]
    for start, end in sorted_intervals[1:]:
        if start <= cur_end:
            if end > cur_end:
                cur_end = end
            continue
        merged.append((cur_start, cur_end))
        cur_start, cur_end = start, end
    merged.append((cur_start, cur_end))
    return merged


def merged_length_ns(intervals: Sequence[Tuple[int, int]]) -> int:
    """Compute union length in ns for possibly overlapping intervals."""
    return sum(end - start for start, end in merge_intervals(intervals))


def _resolve_name(candidate: Optional[str], fallback: Optional[int]) -> str:
    if candidate is not None and candidate != "":
        return candidate
    if fallback is None:
        return "UNKNOWN"
    return f"id:{fallback}"


def load_nvtx_cmd_ranges(
    conn: sqlite3.Connection,
    label_prefix: str,
    allowed_ops: Sequence[str],
    rank_filter: Optional[Sequence[int]],
) -> List[NvtxCmdRange]:
    rows = conn.execute(
        """
        SELECT start, end, text, globalTid
        FROM NVTX_EVENTS
        WHERE text LIKE ?
          AND start IS NOT NULL
          AND end IS NOT NULL
          AND end > start
        ORDER BY start ASC
        """,
        (f"{label_prefix}|%",),
    ).fetchall()
    op_set = set(allowed_ops)
    rank_set = set(rank_filter) if rank_filter is not None else None
    ranges: List[NvtxCmdRange] = []
    for start_ns, end_ns, label, global_tid in rows:
        parsed = parse_cmd_nvtx_label(label, label_prefix)
        if parsed is None:
            continue
        if parsed.get("phase") in ("compute", "comm"):
            # Parent CMD range loader only keeps top-level op windows.
            continue
        op = parsed["op"]
        if op not in op_set:
            continue
        rank = int(parsed["rank"])
        if rank_set is not None and rank not in rank_set:
            continue
        ranges.append(
            NvtxCmdRange(
                start_ns=int(start_ns),
                end_ns=int(end_ns),
                global_pid=derive_global_pid(int(global_tid)),
                rank=rank,
                op=op,
                mg_state=parsed["state"],
                stage_id=parsed["stage"],
                batch_id=parsed["batch"],
                iter_id=parsed["iter"],
                label=label,
            )
        )
    return ranges


def load_nvtx_phase_windows_by_identity(
    conn: sqlite3.Connection,
    label_prefix: str,
    allowed_ops: Sequence[str],
    rank_filter: Optional[Sequence[int]],
    nvtx_ranges: Sequence[NvtxCmdRange],
) -> Dict[Tuple[int, int, str, str, str, str, str, int, int], Dict[str, List[Tuple[int, int]]]]:
    """Load phase NVTX windows and map them to parent CMD windows by identity."""
    if not nvtx_ranges:
        return {}
    op_set = set(allowed_ops)
    rank_set = set(rank_filter) if rank_filter is not None else None

    parents_by_meta: Dict[Tuple[int, int, str, str, str, str, str], List[NvtxCmdRange]] = defaultdict(list)
    for parent in nvtx_ranges:
        key = _range_meta_key(
            global_pid=parent.global_pid,
            rank=parent.rank,
            op=parent.op,
            mg_state=parent.mg_state,
            stage_id=parent.stage_id,
            batch_id=parent.batch_id,
            iter_id=parent.iter_id,
        )
        parents_by_meta[key].append(parent)
    for key in parents_by_meta:
        parents_by_meta[key].sort(key=lambda item: item.start_ns)

    rows = conn.execute(
        """
        SELECT start, end, text, globalTid
        FROM NVTX_EVENTS
        WHERE text LIKE ?
          AND start IS NOT NULL
          AND end IS NOT NULL
          AND end > start
        ORDER BY start ASC
        """,
        (f"{label_prefix}|%",),
    ).fetchall()

    by_identity: Dict[
        Tuple[int, int, str, str, str, str, str, int, int], Dict[str, List[Tuple[int, int]]]
    ] = defaultdict(lambda: {"compute": [], "comm": []})
    for start_ns, end_ns, label, global_tid in rows:
        parsed = parse_cmd_nvtx_label(label, label_prefix)
        if parsed is None:
            continue
        phase = parsed.get("phase")
        if phase not in ("compute", "comm"):
            continue
        op = parsed["op"]
        if op not in op_set:
            continue
        rank = int(parsed["rank"])
        if rank_set is not None and rank not in rank_set:
            continue
        global_pid = derive_global_pid(int(global_tid))
        meta_key = _range_meta_key(
            global_pid=global_pid,
            rank=rank,
            op=op,
            mg_state=parsed["state"],
            stage_id=parsed["stage"],
            batch_id=parsed["batch"],
            iter_id=parsed["iter"],
        )
        parent_candidates = parents_by_meta.get(meta_key, [])
        if not parent_candidates:
            continue
        matched_parent: Optional[NvtxCmdRange] = None
        for parent in parent_candidates:
            if parent.start_ns <= int(start_ns) and parent.end_ns >= int(end_ns):
                matched_parent = parent
                break
        if matched_parent is None:
            continue
        by_identity[range_identity(matched_parent)][phase].append((int(start_ns), int(end_ns)))
    return dict(by_identity)


def load_kernels_for_ranges(
    conn: sqlite3.Connection, nvtx_ranges: Sequence[NvtxCmdRange]
) -> Dict[int, List[KernelRecord]]:
    if not nvtx_ranges:
        return {}
    min_start_ns = min(x.start_ns for x in nvtx_ranges)
    max_end_ns = max(x.end_ns for x in nvtx_ranges)
    pid_values = sorted(set(x.global_pid for x in nvtx_ranges))
    placeholders = ",".join("?" for _ in pid_values)
    query = f"""
        SELECT
            k.start,
            k.end,
            k.streamId,
            k.globalPid,
            s_short.value AS short_name,
            s_dem.value AS demangled_name,
            k.shortName,
            k.demangledName
        FROM CUPTI_ACTIVITY_KIND_KERNEL AS k
        LEFT JOIN StringIds AS s_short
            ON k.shortName = s_short.id
        LEFT JOIN StringIds AS s_dem
            ON k.demangledName = s_dem.id
        WHERE k.end > ?
          AND k.start < ?
          AND k.globalPid IN ({placeholders})
        ORDER BY k.globalPid ASC, k.start ASC
    """
    params: List[int] = [min_start_ns, max_end_ns, *pid_values]
    rows = conn.execute(query, params).fetchall()
    grouped: Dict[int, List[KernelRecord]] = defaultdict(list)
    for (
        start_ns,
        end_ns,
        stream_id,
        global_pid,
        short_name,
        demangled_name,
        short_name_id,
        demangled_name_id,
    ) in rows:
        kernel_name = _resolve_name(demangled_name, demangled_name_id)
        if kernel_name.startswith("id:"):
            kernel_name = _resolve_name(short_name, short_name_id)
        grouped[int(global_pid)].append(
            KernelRecord(
                start_ns=int(start_ns),
                end_ns=int(end_ns),
                stream_id=int(stream_id),
                name=kernel_name,
                is_comm=classify_kernel_name(kernel_name),
            )
        )
    return grouped


def summarize_nvtx_ranges(
    nvtx_ranges: Sequence[NvtxCmdRange],
    kernels_by_pid: Dict[int, List[KernelRecord]],
    phase_windows_by_identity: Optional[
        Dict[Tuple[int, int, str, str, str, str, str, int, int], Dict[str, List[Tuple[int, int]]]]
    ] = None,
) -> List[dict]:
    event_rows: List[dict] = []
    for nvtx_range in nvtx_ranges:
        identity = range_identity(nvtx_range)
        raw_phase_windows = (
            phase_windows_by_identity.get(identity, {})
            if phase_windows_by_identity is not None
            else {}
        )
        compute_phase_windows = merge_intervals(raw_phase_windows.get("compute", []))
        comm_phase_windows = merge_intervals(raw_phase_windows.get("comm", []))
        kernels = kernels_by_pid.get(nvtx_range.global_pid, [])
        compute_ns = 0
        comm_ns = 0
        compute_pure_ns = 0
        kernel_hits = 0
        compute_intervals: List[Tuple[int, int]] = []
        comm_intervals: List[Tuple[int, int]] = []
        total_intervals: List[Tuple[int, int]] = []
        compute_intervals_by_stream: Dict[int, List[Tuple[int, int]]] = defaultdict(list)
        compute_pure_intervals: List[Tuple[int, int]] = []
        compute_pure_intervals_by_stream: Dict[int, List[Tuple[int, int]]] = defaultdict(list)
        compute_by_name_ns: Dict[str, int] = defaultdict(int)
        compute_pure_by_name_ns: Dict[str, int] = defaultdict(int)
        primary_stream_compute_by_name_ns: Dict[str, int] = {}
        primary_stream_compute_pure_by_name_ns: Dict[str, int] = {}
        for kernel in kernels:
            if kernel.end_ns <= nvtx_range.start_ns:
                continue
            if kernel.start_ns >= nvtx_range.end_ns:
                break
            ov_ns = overlap_ns(
                nvtx_range.start_ns, nvtx_range.end_ns, kernel.start_ns, kernel.end_ns
            )
            if ov_ns <= 0:
                continue
            kernel_hits += 1
            overlap_start = max(nvtx_range.start_ns, kernel.start_ns)
            overlap_end = min(nvtx_range.end_ns, kernel.end_ns)
            total_intervals.append((overlap_start, overlap_end))
            if kernel.is_comm:
                comm_ns += ov_ns
                comm_intervals.append((overlap_start, overlap_end))
            else:
                compute_ns += ov_ns
                compute_intervals.append((overlap_start, overlap_end))
                compute_intervals_by_stream[kernel.stream_id].append(
                    (overlap_start, overlap_end)
                )
                compute_by_name_ns[kernel.name] += ov_ns
                if compute_phase_windows:
                    for phase_start_ns, phase_end_ns in compute_phase_windows:
                        phase_overlap_ns = overlap_ns(
                            phase_start_ns, phase_end_ns, kernel.start_ns, kernel.end_ns
                        )
                        if phase_overlap_ns <= 0:
                            continue
                        phase_overlap_start = max(phase_start_ns, kernel.start_ns)
                        phase_overlap_end = min(phase_end_ns, kernel.end_ns)
                        compute_pure_ns += phase_overlap_ns
                        compute_pure_intervals.append((phase_overlap_start, phase_overlap_end))
                        compute_pure_intervals_by_stream[kernel.stream_id].append(
                            (phase_overlap_start, phase_overlap_end)
                        )
                        compute_pure_by_name_ns[kernel.name] += phase_overlap_ns
        if not compute_phase_windows:
            compute_pure_ns = compute_ns
            compute_pure_intervals = list(compute_intervals)
            for stream_id, intervals in compute_intervals_by_stream.items():
                compute_pure_intervals_by_stream[stream_id].extend(intervals)
            for kernel_name, value_ns in compute_by_name_ns.items():
                compute_pure_by_name_ns[kernel_name] += value_ns
        total_ns = compute_ns + comm_ns
        compute_union_ns = merged_length_ns(compute_intervals)
        comm_union_ns = merged_length_ns(comm_intervals)
        total_union_ns = merged_length_ns(total_intervals)
        compute_pure_union_ns = merged_length_ns(compute_pure_intervals)
        primary_stream_id: Optional[int] = None
        primary_stream_union_ns = 0
        if compute_intervals_by_stream:
            primary_stream_id = max(
                compute_intervals_by_stream.keys(),
                key=lambda stream_id: merged_length_ns(
                    compute_intervals_by_stream[stream_id]
                ),
            )
            primary_stream_union_ns = merged_length_ns(
                compute_intervals_by_stream[primary_stream_id]
            )
            primary_stream_compute_by_name_ns = defaultdict(int)
            for kernel in kernels:
                if kernel.is_comm:
                    continue
                if kernel.stream_id != primary_stream_id:
                    continue
                ov_ns = overlap_ns(
                    nvtx_range.start_ns,
                    nvtx_range.end_ns,
                    kernel.start_ns,
                    kernel.end_ns,
                )
                if ov_ns <= 0:
                    continue
                primary_stream_compute_by_name_ns[kernel.name] += ov_ns
        compute_pure_primary_stream_id: Optional[int] = None
        compute_pure_primary_stream_union_ns = 0
        if compute_pure_intervals_by_stream:
            compute_pure_primary_stream_id = max(
                compute_pure_intervals_by_stream.keys(),
                key=lambda stream_id: merged_length_ns(
                    compute_pure_intervals_by_stream[stream_id]
                ),
            )
            compute_pure_primary_stream_union_ns = merged_length_ns(
                compute_pure_intervals_by_stream[compute_pure_primary_stream_id]
            )
            primary_stream_compute_pure_by_name_ns = defaultdict(int)
            for kernel in kernels:
                if kernel.is_comm:
                    continue
                if kernel.stream_id != compute_pure_primary_stream_id:
                    continue
                if compute_phase_windows:
                    for phase_start_ns, phase_end_ns in compute_phase_windows:
                        ov_ns = overlap_ns(
                            phase_start_ns, phase_end_ns, kernel.start_ns, kernel.end_ns
                        )
                        if ov_ns <= 0:
                            continue
                        primary_stream_compute_pure_by_name_ns[kernel.name] += ov_ns
                else:
                    ov_ns = overlap_ns(
                        nvtx_range.start_ns,
                        nvtx_range.end_ns,
                        kernel.start_ns,
                        kernel.end_ns,
                    )
                    if ov_ns <= 0:
                        continue
                    primary_stream_compute_pure_by_name_ns[kernel.name] += ov_ns
        contamination_ns = max(0, compute_ns - compute_pure_ns)
        contamination_pct = (contamination_ns / compute_ns * 100.0) if compute_ns > 0 else 0.0

        wall_ns = nvtx_range.end_ns - nvtx_range.start_ns
        event_rows.append(
            {
                "rank": nvtx_range.rank,
                "op": nvtx_range.op,
                "mg_state": nvtx_range.mg_state,
                "stage_id": nvtx_range.stage_id,
                "batch_id": nvtx_range.batch_id,
                "iter_id": nvtx_range.iter_id,
                "wall_ms": wall_ns / 1_000_000.0,
                # Backward-compatible overlap-sum fields.
                "total_kernel_ms": total_ns / 1_000_000.0,
                "compute_kernel_ms": compute_ns / 1_000_000.0,
                "comm_kernel_ms": comm_ns / 1_000_000.0,
                # New union-based fields to avoid overlap double counting.
                "total_kernel_union_ms": total_union_ns / 1_000_000.0,
                "compute_kernel_union_ms": compute_union_ns / 1_000_000.0,
                "comm_kernel_union_ms": comm_union_ns / 1_000_000.0,
                # Primary-stream compute view for cross-mode comparability.
                "primary_compute_stream_id": primary_stream_id,
                "compute_primary_stream_union_ms": primary_stream_union_ns / 1_000_000.0,
                "compute_stream_count": len(compute_intervals_by_stream),
                # Phase-level pure compute metrics.
                "compute_pure_ms": compute_pure_ns / 1_000_000.0,
                "compute_pure_union_ms": compute_pure_union_ns / 1_000_000.0,
                "compute_pure_primary_stream_id": compute_pure_primary_stream_id,
                "compute_pure_primary_union_ms": (
                    compute_pure_primary_stream_union_ns / 1_000_000.0
                ),
                "phase_compute_window_count": len(compute_phase_windows),
                "phase_comm_window_count": len(comm_phase_windows),
                "contamination_ms": contamination_ns / 1_000_000.0,
                "contamination_pct": contamination_pct,
                # Per-kernel name attribution for shared-kernel filtering in compare.
                "compute_kernel_name_overlap_ms": {
                    name: ns / 1_000_000.0
                    for name, ns in sorted(compute_by_name_ns.items())
                },
                "primary_stream_compute_kernel_name_overlap_ms": {
                    name: ns / 1_000_000.0
                    for name, ns in sorted(primary_stream_compute_by_name_ns.items())
                },
                "compute_pure_kernel_name_overlap_ms": {
                    name: ns / 1_000_000.0
                    for name, ns in sorted(compute_pure_by_name_ns.items())
                },
                "primary_stream_compute_pure_kernel_name_overlap_ms": {
                    name: ns / 1_000_000.0
                    for name, ns in sorted(primary_stream_compute_pure_by_name_ns.items())
                },
                "kernel_count": kernel_hits,
                "label": nvtx_range.label,
            }
        )
    return event_rows


def build_aggregate_rows(event_rows: Sequence[dict]) -> List[dict]:
    grouped: Dict[Tuple[int, str, str, str], List[dict]] = defaultdict(list)
    for row in event_rows:
        key = (row["rank"], row["op"], row["mg_state"], row["stage_id"])
        grouped[key].append(row)
    aggregate_rows: List[dict] = []
    for (rank, op, mg_state, stage_id), rows in sorted(grouped.items()):
        aggregate_rows.append(
            {
                "rank": rank,
                "op": op,
                "mg_state": mg_state,
                "stage_id": stage_id,
                "samples": len(rows),
                "wall_ms_mean": mean(r["wall_ms"] for r in rows),
                "wall_ms_median": median(r["wall_ms"] for r in rows),
                "compute_kernel_ms_mean": mean(r["compute_kernel_ms"] for r in rows),
                "compute_kernel_ms_median": median(
                    r["compute_kernel_ms"] for r in rows
                ),
                "compute_kernel_union_ms_mean": mean(
                    r["compute_kernel_union_ms"] for r in rows
                ),
                "compute_kernel_union_ms_median": median(
                    r["compute_kernel_union_ms"] for r in rows
                ),
                "compute_primary_stream_union_ms_mean": mean(
                    r["compute_primary_stream_union_ms"] for r in rows
                ),
                "compute_primary_stream_union_ms_median": median(
                    r["compute_primary_stream_union_ms"] for r in rows
                ),
                "compute_pure_ms_mean": mean(r["compute_pure_ms"] for r in rows),
                "compute_pure_ms_median": median(r["compute_pure_ms"] for r in rows),
                "compute_pure_union_ms_mean": mean(
                    r["compute_pure_union_ms"] for r in rows
                ),
                "compute_pure_union_ms_median": median(
                    r["compute_pure_union_ms"] for r in rows
                ),
                "compute_pure_primary_union_ms_mean": mean(
                    r["compute_pure_primary_union_ms"] for r in rows
                ),
                "compute_pure_primary_union_ms_median": median(
                    r["compute_pure_primary_union_ms"] for r in rows
                ),
                "contamination_ms_mean": mean(r["contamination_ms"] for r in rows),
                "contamination_ms_median": median(r["contamination_ms"] for r in rows),
                "contamination_pct_mean": mean(r["contamination_pct"] for r in rows),
                "contamination_pct_median": median(r["contamination_pct"] for r in rows),
                "comm_kernel_ms_mean": mean(r["comm_kernel_ms"] for r in rows),
                "comm_kernel_ms_median": median(r["comm_kernel_ms"] for r in rows),
                "comm_kernel_union_ms_mean": mean(
                    r["comm_kernel_union_ms"] for r in rows
                ),
                "comm_kernel_union_ms_median": median(
                    r["comm_kernel_union_ms"] for r in rows
                ),
                "total_kernel_ms_mean": mean(r["total_kernel_ms"] for r in rows),
                "total_kernel_ms_median": median(r["total_kernel_ms"] for r in rows),
                "total_kernel_union_ms_mean": mean(
                    r["total_kernel_union_ms"] for r in rows
                ),
                "total_kernel_union_ms_median": median(
                    r["total_kernel_union_ms"] for r in rows
                ),
                "kernel_count_mean": mean(r["kernel_count"] for r in rows),
            }
        )
    return aggregate_rows


def _format_table(aggregate_rows: Sequence[dict]) -> List[str]:
    lines: List[str] = []
    lines.append(
        "| rank | op | mg_state | stage_id | samples | "
        "compute_ms_mean(overlap) | compute_ms_mean(union) | "
        "compute_ms_mean(primary_union) | compute_pure_ms_mean(primary_union) | "
        "contamination_pct_mean | comm_ms_mean(overlap) | comm_ms_mean(union) | wall_ms_mean |"
    )
    lines.append("|---:|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for row in aggregate_rows:
        lines.append(
            "| "
            f"{row['rank']} | {row['op']} | {row['mg_state']} | {row['stage_id']} | "
            f"{row['samples']} | {row['compute_kernel_ms_mean']:.4f} | "
            f"{row['compute_kernel_union_ms_mean']:.4f} | "
            f"{row['compute_primary_stream_union_ms_mean']:.4f} | "
            f"{row['compute_pure_primary_union_ms_mean']:.4f} | "
            f"{row['contamination_pct_mean']:.2f}% | "
            f"{row['comm_kernel_ms_mean']:.4f} | {row['comm_kernel_union_ms_mean']:.4f} | "
            f"{row['wall_ms_mean']:.4f} |"
        )
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Analyze Nsight sqlite using CMD NVTX labels for compute-only breakdown."
    )
    parser.add_argument("--sqlite", type=Path, required=True)
    parser.add_argument(
        "--label-prefix",
        type=str,
        default="cmd_trace",
        help="CMD NVTX label prefix, must match --trace-kernel-ground-truth-prefix.",
    )
    parser.add_argument(
        "--ops",
        type=str,
        default=",".join(DEFAULT_OPS),
        help="Comma-separated op list.",
    )
    parser.add_argument(
        "--ranks",
        type=str,
        default="",
        help="Optional comma-separated rank filter; empty means all ranks.",
    )
    parser.add_argument("--report-path", type=Path, default=None)
    parser.add_argument("--json-path", type=Path, default=None)
    args = parser.parse_args()

    if not args.sqlite.exists():
        print(f"[ERROR] sqlite file does not exist: {args.sqlite}")
        return 2
    try:
        ops = parse_csv_strs(args.ops)
    except ValueError as exc:
        print(f"[ERROR] Invalid --ops: {exc}")
        return 2
    try:
        rank_filter = parse_csv_ints(args.ranks)
    except ValueError as exc:
        print(f"[ERROR] Invalid --ranks: {exc}")
        return 2

    conn = sqlite3.connect(str(args.sqlite))
    try:
        nvtx_ranges = load_nvtx_cmd_ranges(
            conn=conn, label_prefix=args.label_prefix, allowed_ops=ops, rank_filter=rank_filter
        )
        if not nvtx_ranges:
            print(
                "[ERROR] No CMD NVTX ranges found. "
                "Please verify trace-kernel-ground-truth labels and filters."
            )
            return 1
        phase_windows_by_identity = load_nvtx_phase_windows_by_identity(
            conn=conn,
            label_prefix=args.label_prefix,
            allowed_ops=ops,
            rank_filter=rank_filter,
            nvtx_ranges=nvtx_ranges,
        )
        kernels_by_pid = load_kernels_for_ranges(conn, nvtx_ranges)
        event_rows = summarize_nvtx_ranges(
            nvtx_ranges,
            kernels_by_pid,
            phase_windows_by_identity=phase_windows_by_identity,
        )
        aggregate_rows = build_aggregate_rows(event_rows)
    finally:
        conn.close()

    report_lines: List[str] = []
    report_lines.append(f"sqlite={args.sqlite}")
    report_lines.append(f"label_prefix={args.label_prefix}")
    report_lines.append(f"ops={','.join(ops)}")
    report_lines.append(
        "ranks="
        + ("ALL" if rank_filter is None else ",".join(str(x) for x in rank_filter))
    )
    report_lines.append(f"phase_window_parents={len(phase_windows_by_identity)}")
    report_lines.append(f"event_rows={len(event_rows)}")
    report_lines.append(f"aggregate_rows={len(aggregate_rows)}")
    report_lines.extend(_format_table(aggregate_rows))
    report_text = "\n".join(report_lines)
    print(report_text)

    if args.report_path is not None:
        args.report_path.parent.mkdir(parents=True, exist_ok=True)
        args.report_path.write_text(report_text + "\n")
        print(f"[INFO] Report written to {args.report_path}")

    if args.json_path is not None:
        args.json_path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "sqlite": str(args.sqlite),
            "label_prefix": args.label_prefix,
            "ops": ops,
            "ranks": rank_filter,
            "event_rows": event_rows,
            "aggregate_rows": aggregate_rows,
        }
        args.json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
        print(f"[INFO] JSON written to {args.json_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
