#!/usr/bin/env python3
"""Extract kernel-level compute/comm breakdown from Nsight Systems sqlite traces.

This script uses CMD-level NVTX labels generated by `--trace-kernel-ground-truth`:
  <prefix>|rank=<r>|op=<op>|state=<mg_state>|stage=<s>|batch=<b>|iter=<i>

For each NVTX range, it aggregates overlapped CUDA kernels from the same process:
  - compute_kernel_ms: kernels whose names do NOT contain "nccl"
  - comm_kernel_ms: kernels whose names contain "nccl"
  - total_kernel_ms: compute + comm

The output JSON can be consumed by compare_qwen_nsys_compute_only.py.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, median
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


DEFAULT_OPS = ("forward_step", "backward_step", "optimizer_step")
GLOBAL_TID_LOCAL_MASK = (1 << 24) - 1


@dataclass(frozen=True)
class NvtxCmdRange:
    start_ns: int
    end_ns: int
    global_pid: int
    rank: int
    op: str
    mg_state: str
    stage_id: str
    batch_id: str
    iter_id: str
    label: str


@dataclass(frozen=True)
class KernelRecord:
    start_ns: int
    end_ns: int
    name: str
    is_comm: bool


def parse_csv_ints(raw: str) -> Optional[List[int]]:
    if raw.strip() == "":
        return None
    values: List[int] = []
    for token in raw.split(","):
        item = token.strip()
        if not item:
            continue
        values.append(int(item))
    if not values:
        return None
    return values


def parse_csv_strs(raw: str) -> List[str]:
    values = [token.strip() for token in raw.split(",") if token.strip()]
    if not values:
        raise ValueError("Empty --ops list.")
    return values


def derive_global_pid(global_tid: int) -> int:
    """Convert NVTX globalTid into the globalPid domain used by CUPTI kernels."""
    return global_tid & (~GLOBAL_TID_LOCAL_MASK)


def parse_cmd_nvtx_label(label: str, prefix: str) -> Optional[Dict[str, str]]:
    """Parse CMD NVTX label into key/value mapping."""
    prefix_token = f"{prefix}|"
    if not label.startswith(prefix_token):
        return None
    fields = label[len(prefix_token) :].split("|")
    mapping: Dict[str, str] = {}
    for field in fields:
        if "=" not in field:
            continue
        key, value = field.split("=", 1)
        mapping[key] = value
    required = ("rank", "op", "state", "stage", "batch", "iter")
    if any(key not in mapping for key in required):
        return None
    return mapping


def classify_kernel_name(kernel_name: str) -> bool:
    """Return True when kernel is communication kernel."""
    return "nccl" in kernel_name.lower()


def overlap_ns(window_start: int, window_end: int, kernel_start: int, kernel_end: int) -> int:
    lo = max(window_start, kernel_start)
    hi = min(window_end, kernel_end)
    return max(0, hi - lo)


def _resolve_name(candidate: Optional[str], fallback: Optional[int]) -> str:
    if candidate is not None and candidate != "":
        return candidate
    if fallback is None:
        return "UNKNOWN"
    return f"id:{fallback}"


def load_nvtx_cmd_ranges(
    conn: sqlite3.Connection,
    label_prefix: str,
    allowed_ops: Sequence[str],
    rank_filter: Optional[Sequence[int]],
) -> List[NvtxCmdRange]:
    rows = conn.execute(
        """
        SELECT start, end, text, globalTid
        FROM NVTX_EVENTS
        WHERE text LIKE ?
          AND start IS NOT NULL
          AND end IS NOT NULL
          AND end > start
        ORDER BY start ASC
        """,
        (f"{label_prefix}|%",),
    ).fetchall()
    op_set = set(allowed_ops)
    rank_set = set(rank_filter) if rank_filter is not None else None
    ranges: List[NvtxCmdRange] = []
    for start_ns, end_ns, label, global_tid in rows:
        parsed = parse_cmd_nvtx_label(label, label_prefix)
        if parsed is None:
            continue
        op = parsed["op"]
        if op not in op_set:
            continue
        rank = int(parsed["rank"])
        if rank_set is not None and rank not in rank_set:
            continue
        ranges.append(
            NvtxCmdRange(
                start_ns=int(start_ns),
                end_ns=int(end_ns),
                global_pid=derive_global_pid(int(global_tid)),
                rank=rank,
                op=op,
                mg_state=parsed["state"],
                stage_id=parsed["stage"],
                batch_id=parsed["batch"],
                iter_id=parsed["iter"],
                label=label,
            )
        )
    return ranges


def load_kernels_for_ranges(
    conn: sqlite3.Connection, nvtx_ranges: Sequence[NvtxCmdRange]
) -> Dict[int, List[KernelRecord]]:
    if not nvtx_ranges:
        return {}
    min_start_ns = min(x.start_ns for x in nvtx_ranges)
    max_end_ns = max(x.end_ns for x in nvtx_ranges)
    pid_values = sorted(set(x.global_pid for x in nvtx_ranges))
    placeholders = ",".join("?" for _ in pid_values)
    query = f"""
        SELECT
            k.start,
            k.end,
            k.globalPid,
            s_short.value AS short_name,
            s_dem.value AS demangled_name,
            k.shortName,
            k.demangledName
        FROM CUPTI_ACTIVITY_KIND_KERNEL AS k
        LEFT JOIN StringIds AS s_short
            ON k.shortName = s_short.id
        LEFT JOIN StringIds AS s_dem
            ON k.demangledName = s_dem.id
        WHERE k.end > ?
          AND k.start < ?
          AND k.globalPid IN ({placeholders})
        ORDER BY k.globalPid ASC, k.start ASC
    """
    params: List[int] = [min_start_ns, max_end_ns, *pid_values]
    rows = conn.execute(query, params).fetchall()
    grouped: Dict[int, List[KernelRecord]] = defaultdict(list)
    for (
        start_ns,
        end_ns,
        global_pid,
        short_name,
        demangled_name,
        short_name_id,
        demangled_name_id,
    ) in rows:
        kernel_name = _resolve_name(demangled_name, demangled_name_id)
        if kernel_name.startswith("id:"):
            kernel_name = _resolve_name(short_name, short_name_id)
        grouped[int(global_pid)].append(
            KernelRecord(
                start_ns=int(start_ns),
                end_ns=int(end_ns),
                name=kernel_name,
                is_comm=classify_kernel_name(kernel_name),
            )
        )
    return grouped


def summarize_nvtx_ranges(
    nvtx_ranges: Sequence[NvtxCmdRange], kernels_by_pid: Dict[int, List[KernelRecord]]
) -> List[dict]:
    event_rows: List[dict] = []
    for nvtx_range in nvtx_ranges:
        kernels = kernels_by_pid.get(nvtx_range.global_pid, [])
        compute_ns = 0
        comm_ns = 0
        kernel_hits = 0
        for kernel in kernels:
            if kernel.end_ns <= nvtx_range.start_ns:
                continue
            if kernel.start_ns >= nvtx_range.end_ns:
                break
            ov_ns = overlap_ns(
                nvtx_range.start_ns, nvtx_range.end_ns, kernel.start_ns, kernel.end_ns
            )
            if ov_ns <= 0:
                continue
            kernel_hits += 1
            if kernel.is_comm:
                comm_ns += ov_ns
            else:
                compute_ns += ov_ns
        total_ns = compute_ns + comm_ns
        wall_ns = nvtx_range.end_ns - nvtx_range.start_ns
        event_rows.append(
            {
                "rank": nvtx_range.rank,
                "op": nvtx_range.op,
                "mg_state": nvtx_range.mg_state,
                "stage_id": nvtx_range.stage_id,
                "batch_id": nvtx_range.batch_id,
                "iter_id": nvtx_range.iter_id,
                "wall_ms": wall_ns / 1_000_000.0,
                "total_kernel_ms": total_ns / 1_000_000.0,
                "compute_kernel_ms": compute_ns / 1_000_000.0,
                "comm_kernel_ms": comm_ns / 1_000_000.0,
                "kernel_count": kernel_hits,
                "label": nvtx_range.label,
            }
        )
    return event_rows


def build_aggregate_rows(event_rows: Sequence[dict]) -> List[dict]:
    grouped: Dict[Tuple[int, str, str, str], List[dict]] = defaultdict(list)
    for row in event_rows:
        key = (row["rank"], row["op"], row["mg_state"], row["stage_id"])
        grouped[key].append(row)
    aggregate_rows: List[dict] = []
    for (rank, op, mg_state, stage_id), rows in sorted(grouped.items()):
        aggregate_rows.append(
            {
                "rank": rank,
                "op": op,
                "mg_state": mg_state,
                "stage_id": stage_id,
                "samples": len(rows),
                "wall_ms_mean": mean(r["wall_ms"] for r in rows),
                "wall_ms_median": median(r["wall_ms"] for r in rows),
                "compute_kernel_ms_mean": mean(r["compute_kernel_ms"] for r in rows),
                "compute_kernel_ms_median": median(
                    r["compute_kernel_ms"] for r in rows
                ),
                "comm_kernel_ms_mean": mean(r["comm_kernel_ms"] for r in rows),
                "comm_kernel_ms_median": median(r["comm_kernel_ms"] for r in rows),
                "total_kernel_ms_mean": mean(r["total_kernel_ms"] for r in rows),
                "total_kernel_ms_median": median(r["total_kernel_ms"] for r in rows),
                "kernel_count_mean": mean(r["kernel_count"] for r in rows),
            }
        )
    return aggregate_rows


def _format_table(aggregate_rows: Sequence[dict]) -> List[str]:
    lines: List[str] = []
    lines.append(
        "| rank | op | mg_state | stage_id | samples | "
        "compute_ms_mean | compute_ms_median | comm_ms_mean | wall_ms_mean |"
    )
    lines.append("|---:|---|---|---:|---:|---:|---:|---:|---:|")
    for row in aggregate_rows:
        lines.append(
            "| "
            f"{row['rank']} | {row['op']} | {row['mg_state']} | {row['stage_id']} | "
            f"{row['samples']} | {row['compute_kernel_ms_mean']:.4f} | "
            f"{row['compute_kernel_ms_median']:.4f} | {row['comm_kernel_ms_mean']:.4f} | "
            f"{row['wall_ms_mean']:.4f} |"
        )
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Analyze Nsight sqlite using CMD NVTX labels for compute-only breakdown."
    )
    parser.add_argument("--sqlite", type=Path, required=True)
    parser.add_argument(
        "--label-prefix",
        type=str,
        default="cmd_trace",
        help="CMD NVTX label prefix, must match --trace-kernel-ground-truth-prefix.",
    )
    parser.add_argument(
        "--ops",
        type=str,
        default=",".join(DEFAULT_OPS),
        help="Comma-separated op list.",
    )
    parser.add_argument(
        "--ranks",
        type=str,
        default="",
        help="Optional comma-separated rank filter; empty means all ranks.",
    )
    parser.add_argument("--report-path", type=Path, default=None)
    parser.add_argument("--json-path", type=Path, default=None)
    args = parser.parse_args()

    if not args.sqlite.exists():
        print(f"[ERROR] sqlite file does not exist: {args.sqlite}")
        return 2
    try:
        ops = parse_csv_strs(args.ops)
    except ValueError as exc:
        print(f"[ERROR] Invalid --ops: {exc}")
        return 2
    try:
        rank_filter = parse_csv_ints(args.ranks)
    except ValueError as exc:
        print(f"[ERROR] Invalid --ranks: {exc}")
        return 2

    conn = sqlite3.connect(str(args.sqlite))
    try:
        nvtx_ranges = load_nvtx_cmd_ranges(
            conn=conn, label_prefix=args.label_prefix, allowed_ops=ops, rank_filter=rank_filter
        )
        if not nvtx_ranges:
            print(
                "[ERROR] No CMD NVTX ranges found. "
                "Please verify trace-kernel-ground-truth labels and filters."
            )
            return 1
        kernels_by_pid = load_kernels_for_ranges(conn, nvtx_ranges)
        event_rows = summarize_nvtx_ranges(nvtx_ranges, kernels_by_pid)
        aggregate_rows = build_aggregate_rows(event_rows)
    finally:
        conn.close()

    report_lines: List[str] = []
    report_lines.append(f"sqlite={args.sqlite}")
    report_lines.append(f"label_prefix={args.label_prefix}")
    report_lines.append(f"ops={','.join(ops)}")
    report_lines.append(
        "ranks="
        + ("ALL" if rank_filter is None else ",".join(str(x) for x in rank_filter))
    )
    report_lines.append(f"event_rows={len(event_rows)}")
    report_lines.append(f"aggregate_rows={len(aggregate_rows)}")
    report_lines.extend(_format_table(aggregate_rows))
    report_text = "\n".join(report_lines)
    print(report_text)

    if args.report_path is not None:
        args.report_path.parent.mkdir(parents=True, exist_ok=True)
        args.report_path.write_text(report_text + "\n")
        print(f"[INFO] Report written to {args.report_path}")

    if args.json_path is not None:
        args.json_path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "sqlite": str(args.sqlite),
            "label_prefix": args.label_prefix,
            "ops": ops,
            "ranks": rank_filter,
            "event_rows": event_rows,
            "aggregate_rows": aggregate_rows,
        }
        args.json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
        print(f"[INFO] JSON written to {args.json_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
